# Generated by Django 3.0.6 on 2020-06-22 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowedBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField()),
                ('dateofborrowing', models.DateField()),
                ('returndate', models.DateField()),
                ('book_isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookisbn', to='books.Book')),
            ],
        ),
    ]
