# Generated by Django 2.0.3 on 2020-06-23 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowedbooks',
            name='paid',
        ),
        migrations.AddField(
            model_name='borrowedbooks',
            name='member_email',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='username', to=settings.AUTH_USER_MODEL),
        ),
    ]
